### ISSUE TITLE
State Caching

### ISSUE THREAD

**Issue by IGJoshua** [IGJoshua/discljord#32]
Discord sends a lot of state to bots, much of which is expected to be cached to help reduce the amount of requests that need to be made to the Rest API. Currently there are no tools for users of discljord to have that state cached automatically.

I think that it would be a good idea to add middleware (#31) for caching all this state in an agent, which is then accessible by user code.

**Comment by pmonks** [comment]
Some ideas for useful information to cache (and you may already have thought of these, and more):

1. User information (e.g. user-id -> username -> guild-id+nickname)

2. Channel information (e.g. channel-id -> guild-id+channel-name)

**Comment by IGJoshua** [comment]
This has been implemented in the latest develop.

**Comment by pmonks** [comment]
Any chance of adding an example to the docs, showing how to use this new functionality?

From reading [the code](https://github.com/IGJoshua/discljord/blob/develop/src/discljord/events/state.clj) I _think_ that the responsibility for creating the state atom and calling either `caching-middleware` or `caching-transducer` (which one, and in what circumstances?) from the message pump lies with the client app, but I'm not 100% certain of my reading...

**Comment by IGJoshua** [comment]
Absolutely I can get some docs into the project. I'll update the project wiki today. I'll re-close this issue once that's been added.

**Comment by IGJoshua** [comment]
Documentation has been added to the project wiki! I'm closing this out again.
