### ISSUE TITLE
Consider switching to a logging interface (e.g. clojure.tools.logging), rather than an implementation (timbre)

### ISSUE THREAD

**Issue by pmonks** [IGJoshua/discljord#41]
Currently `discljord` uses [`timbre`](https://github.com/ptaoussanis/timbre) for logging, which is both a logging interface and an implementation.  It appears to be quite difficult to swap out another implementation underneath `timbre`, meaning that downstream consumers of `discljord` appear to be limited to using `timbre` too.

**Comment by pmonks** [comment]
Although I've managed to get `discljord` to emit output via `logback` (my preferred logging implementation), some of `timbre`'s data elements are mapped incorrectly, hampering both the readability of the output and configurability.  I'm still in the process of trying to determine if this is user error on my part, or just an as-designed feature of `timbre` (i.e. it's just not designed to have its implementation replaced with something else).

**Comment by IGJoshua** [comment]
I've published a release candidate with clojure.tools.logging as the implementation, further tracking of this can be viewed under #40

**Comment by pmonks** [comment]
Looking great!  I just took RC2 for a spin, and the logging oddities I was seeing earlier have all disappeared.
