### ISSUE TITLE
Gateway v8 Support

### ISSUE THREAD

**Issue by IGJoshua** [IGJoshua/discljord#59]
A couple weeks ago Discord finally released and documented the v8 of the gateway, and deprecated v6. Following is a list of expected changes.

- [x] Make intents required
- [x] Update retry after rate limit to seconds
- [x] Update other rate limit headers to millis
- [x] Update endpoints to match new versions
- [ ] Remove role caching from presence update events
- [x] Update create ban to use correct parameter name

**Comment by seylerius** [comment]
This library looks really great. I'm currently looking into making a bot for some custom features that just aren't available (or are cumbersome to implement), and one of them is honestly going to be a whole lot easier with v8. What's the current state of this, and is there any way I can pitch in?

**Comment by IGJoshua** [comment]
@seylerius We actually already have v8 support, I'd just forgotten to close the issue! This was completed as a part of the 1.2.0 release, which has been sitting in RC for about a week.

At the moment the main next step is some design work for a commands library to include within discljord, and the best way to contribute there would be to create your own open-source library that provides a command system to hook into discljord, with the potential of having ideas from it pulled into the mainline library.

**Comment by seylerius** [comment]
Wonderful! I'll get on that, then, and build the commands-and-triggers
wrapper I'm thinking about around 1.2.0 as part of making my bot. What's
the simplest way to depend on that version, given that it's still in RC?

**Comment by IGJoshua** [comment]
Version 1.2.0 was released today to full version, so you can start building it today!

**Comment by seylerius** [comment]
Awesome, thank you!
