### ISSUE TITLE
Feature request: Make embed support

### ISSUE THREAD

**Issue by LoadingBG** [IGJoshua/discljord#62]
Discord bots can send embeds instead of normal text messages. I want to send embeds but I don't see anything in the documentation about embeds except in `discljord.messaging/create-message!` which accepts an embed in the keyword arguments (I assume). Is there support for embeds and if so, how can I create one?

**Comment by JohnnyJayJay** [comment]
Yes, there is support for embeds and the keyword arg `embed` in `create-message` enables it.
Embeds are represented as regular Clojure maps, so this is what sending a message with an embed might look like:
```clj
(create-message! conn channel-id :embed 
  {:author {:name "Johnny"                      
            :icon_url "https://example.com/someimage.png"}              
   :description "This is an embed"            
   :color 0x4e87e6               
   :fields [{:name "Field 1" 
             :value "Hello" 
             :inline true}]               
   :footer {:text "Footer text"}})
```
That would result in the following embed:
![](https://i.imgur.com/Fy0nWoH.png)

I think you get the idea, it's essentially just the JSON map that is finally passed to Discord, for more info see [here](https://discord.com/developers/docs/resources/channel#embed-object).
