### ISSUE TITLE
Reduce thread count for HttpClient

### ISSUE THREAD

**Issue by IGJoshua** [IGJoshua/discljord#65]
The Jetty http client is starting up many threads per discljord connection which is spun up on the JVM. This can be a problem for people who are using the library with the intention of having many instances of bots active on the same box.

It looks like the solution to this will be to set an executor when creating the `WebSocketClient` in `connections/impl.clj:209`, but I need to consider how people might want to use this. Potentially they will want a new executor per shard, etc., and so I must provide a way for the user to make decisions at runtime about this. At the moment I think this will be done by having an optional lambda on the connection entry points which will be called with the shard id and must return an executor to use on that shard's client.

In the mean time, if a user needs to be able to support this on an existing version of discljord, a patch may be made pretty easily which includes an atom in the impl namespace which has the executor in it to be used when constructing the client, and can be `reset!` before the connection is made.

**Comment by IGJoshua** [comment]
Connected to this issue it appears that on error, old websocket connections are not closed before new ones are started, which is part of the cause for this issue for the people who reported it.

**Comment by manoj-helpshift** [comment]
@IGJoshua Summary of our last discussion:

`discljord` internally using `gniazdo` library to maintain websocket connection. For every websocket management, `gniazdo` create 9-10 thread to alive client side websocket connection with server.

`gniazdo` provides multiple callback function for connection status, one of the API is `:on-error` which called whenever some error occured. 

Reference: [https://github.com/stalefruits/gniazdo#gniazdocoreconnect-uri--options](https://github.com/stalefruits/gniazdo#gniazdocoreconnect-uri--options)

In our application, we are receiving following error:

```
ns: discljord.connections.impl

Websocket errored #error { :cause Broken pipe :via [{:type java.io.IOException
   :message Broken pipe
   :at [org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint flush SslConnection.java 1089]}]
 :trace
 [[org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint flush SslConnection.java 1089]
  [org.eclipse.jetty.io.WriteFlusher flush WriteFlusher.java 422]
  [org.eclipse.jetty.io.WriteFlusher write WriteFlusher.java 277]
  [org.eclipse.jetty.io.AbstractEndPoint write AbstractEndPoint.java 381]
  [org.eclipse.jetty.websocket.common.io.FrameFlusher flush FrameFlusher.java 264]
  [org.eclipse.jetty.websocket.common.io.FrameFlusher process FrameFlusher.java 193]
  [org.eclipse.jetty.util.IteratingCallback processing IteratingCallback.java 241]
  [org.eclipse.jetty.util.IteratingCallback iterate IteratingCallback.java 223]
  [org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection outgoingFrame AbstractWebSocketConnection.java 581]
  [org.eclipse.jetty.websocket.client.io.WebSocketClientConnection outgoingFrame WebSocketClientConnection.java 58]
  [org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection close AbstractWebSocketConnection.java 181]
  [org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection onFillable AbstractWebSocketConnection.java 510]
  [org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection onFillable AbstractWebSocketConnection.java 440]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded AbstractConnection.java 311]
  [org.eclipse.jetty.io.FillInterest fillable FillInterest.java 103]
  [org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint onFillable SslConnection.java 543]
  [org.eclipse.jetty.io.ssl.SslConnection onFillable SslConnection.java 398]
  [org.eclipse.jetty.io.ssl.SslConnection$2 succeeded SslConnection.java 161]
  [org.eclipse.jetty.io.FillInterest fillable FillInterest.java 103]
  [org.eclipse.jetty.io.ChannelEndPoint$2 run ChannelEndPoint.java 117]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask EatWhatYouKill.java 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce EatWhatYouKill.java 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce EatWhatYouKill.java 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run EatWhatYouKill.java 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run ReservedThreadExecutor.java 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob QueuedThreadPool.java 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run QueuedThreadPool.java 905]
  [java.lang.Thread run Thread.java 748]]}
```

When `:on-error` callback called in internal Websocket connection, `discljord`  `handle-shard-fx! :on-error` API called and  library not closing old WebSocket connection before created new websocket connection and which causing thread count to increase by 10. 

```
(defmethod handle-shard-fx! :error
  [heartbeat-ch url token shard [_ err]]
  (log/error err "Error encountered on shard" (:id shard))
  {:shard shard
   :effects []})
```

Function which create new websocket connection and replace the variable in shard.

```
(defmethod handle-connection-event! :connect
  [{:keys [heartbeat-ch event-ch compress] :as shard} url _]
  (log/info "Connecting shard" (:id shard))
  (when heartbeat-ch
    (a/close! heartbeat-ch))
  (let [event-ch (a/chan 100)
        websocket (try (connect-websocket! buffer-size url event-ch compress)
                       (catch Exception err
                         (log/warn "Failed to connect a websocket" err)
                         (.stop ^WebSocketClient (:client (ex-data err)))
                         nil))]
    (when-not websocket
      (a/put! event-ch [:disconnect nil "Failed to connect"]))
    {:shard (assoc (dissoc shard
                           :heartbeat-ch)
                   :websocket websocket
                   :event-ch event-ch)
     :effects []}))
```

Discljord library closing websocket connection only when disconnect event occured.

Thread count also increased in following cases:

1. When discord server want to re-verify the current connection with :identify event and discljord need to :resume the connection.
2. Client internet connection is down for 20-30 sec, WebSocket connection throw an exception, in this case also thread count increased by 10.

    ```
    [2021-03-19 17:29:58,311] WARN  discljord.connections.impl: Failed to connect a websocket #error {
     :cause gateway.discord.gg: nodename nor servname provided, or not known
     :via
     [{:type clojure.lang.ExceptionInfo
       :message Failed to connect a websocket
       :data {:client #object[org.eclipse.jetty.websocket.client.WebSocketClient 0x7f79b7ea WebSocketClient@159f6f38[httpClient=HttpClient@f42d1f0{STARTED},openSessions.size=0]]}
       :at [discljord.connections.impl$connect_websocket_BANG_ invokeStatic impl.clj 253]}
      {:type java.net.UnknownHostException
       :message gateway.discord.gg: nodename nor servname provided, or not known
       :at [java.net.Inet6AddressImpl lookupAllHostAddr Inet6AddressImpl.java -2]}]
     :trace
     [[java.net.Inet6AddressImpl lookupAllHostAddr Inet6AddressImpl.java -2]
      [java.net.InetAddress$2 lookupAllHostAddr InetAddress.java 929]
      [java.net.InetAddress getAddressesFromNameService InetAddress.java 1324]
      [java.net.InetAddress getAllByName0 InetAddress.java 1277]
      [java.net.InetAddress getAllByName InetAddress.java 1193]
      [java.net.InetAddress getAllByName InetAddress.java 1127]
      [org.eclipse.jetty.util.SocketAddressResolver$Async lambda$resolve$1 SocketAddressResolver.java 170]
      [org.eclipse.jetty.util.thread.QueuedThreadPool runJob QueuedThreadPool.java 773]
      [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run QueuedThreadPool.java 905]
      [java.lang.Thread run Thread.java 748]]}

    ```

**Comment by IGJoshua** [comment]
I'm taking a look at this today, going to try and put out a hotfix. I'll comment again with the status soon.

**Comment by IGJoshua** [comment]
Alright, so I have a snapshot release out, `1.2.3-SNAPSHOT` available on Clojars. If you could test this again, that'd be fantastic.

**Comment by manoj-helpshift** [comment]
As discussed on the discord server, 
 During my verification, if the client machine internet is down for more than 1 min, getting the following exception and discord bot disconnected. If client machine internet comes online, the bot is not re-connecting:


```
[2021-04-17 18:05:35,224] INFO  discljord.connections.impl: Reconnecting due to zombie heartbeat on shard 0
Exception in thread "async-dispatch-6" [2021-04-17 18:05:35,225] INFO  discljord.connections.impl: Exiting the shard loop
java.lang.IllegalArgumentException: No implementation of method: :close of protocol: #'gniazdo.core/Client found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at gniazdo.core$fn__23349$G__23331__23360.invoke(core.clj:37)
	at discljord.connections.impl$fn__24019.invokeStatic(impl.clj:592)
	at discljord.connections.impl$fn__24019.invoke(impl.clj:586)
	at clojure.lang.MultiFn.invoke(MultiFn.java:252)
	at discljord.connections.impl$step_shard_BANG_$event_fn__23615$fn__23618.invoke(impl.clj:413)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at discljord.connections.impl$step_shard_BANG_$event_fn__23615.invoke(impl.clj:409)
	at discljord.connections.impl$step_shard_BANG_$fn__23759$state_machine__9379__auto____23786$fn__23788.invoke(impl.clj:436)
	at discljord.connections.impl$step_shard_BANG_$fn__23759$state_machine__9379__auto____23786.invoke(impl.clj:421)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at discljord.connections.impl$step_shard_BANG_$fn__23759.invoke(impl.clj:421)Event data: nil

	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by IGJoshua** [comment]
I'm taking a crack at this today, hopefully I can get it fixed.

**Comment by IGJoshua** [comment]
Alright, it looks like there was an issue I hadn't seen before where the websocket will sometimes be closed by jetty, causing the websockets to sometimes be nil in unexpected places. @manoj-helpshift would you be able to re-test with the git dep on commit `5bc1c27d022cba32a8acf2396b8481c85e8bb8be`?

**Comment by manoj-helpshift** [comment]
Ack...will re-verify in some time.

**Comment by IGJoshua** [comment]
Thanks

**Comment by manoj-helpshift** [comment]
@IGJoshua Today, I tested the thread count with the latest patch and thread count still increasing with every re-connection.
Please check the attached file for detailed logs: 
[22-May-2021-Latest-patch.log](https://github.com/IGJoshua/discljord/files/6526932/22-May-2021-Latest-patch.log)

Let me know if you need more info on this

**Comment by manoj-helpshift** [comment]
@IGJoshua I further checked the issue in new library and identified the root cause as:
1. When WS connection disconnect, discljord add event in `event-ch` and it further processed by `handle-websocket-event :disconnect` fn.
2. In `handle-websocket-event :disconnect` function, when building `shard` object when `status-code` is available, discljord lib code removing `:websocket` object due to this, WS connection not closed during re-connect/connect.


```
(defmethod handle-websocket-event :disconnect
  [{:keys [websocket] :as shard} [_ stop-code msg]]
  (if shard
    {:shard (if stop-code
              (do
                ;; TODO: Sample code for fix
                (when websocket
                  (log/debug "MANOJ: closing the websocket")
                  (ws/close websocket stop-code "Manoj: Reconnecting error"))
                (assoc (dissoc shard :websocket)
                         :stop-code stop-code
                         :disconnect-msg msg))
              shard)
     :effects [(cond
                 (re-shard-stop-code? stop-code) [:re-shard]
                 (and *stop-on-fatal-code*
                      (fatal-code? stop-code))   [:disconnect-all]
                 (user-error-code? stop-code)  (do
                                                 (log/fatal (str "Received stop code " stop-code
                                                                 " which can only occur on user error."
                                                                 " Disconecting bot."))
                                                 [:disconnect-all])
                 :otherwise                      [:reconnect])]}
    {:shard nil
     :effects []}))
```

We have two options: 
1. Pass the `websocket` object in shard as it coming and during re-connect/connect, close it.
2. During shard building, close the WS connect and then dissoc the `websocket` key.

@IGJoshua  I can push the commit, plz check ^

**Comment by manoj-helpshift** [comment]
I checked above solution in my local env and thread count is not increasing on re-connection/resume session.

**Comment by IGJoshua** [comment]
The release is out with a fix similar to this. Let me know if you see any issues with this. If not, I'll close out this issue.

**Comment by manoj-helpshift** [comment]
Thank you @IGJoshua , I verified the thread count issue with the latest tag `1.2.3`, thread count is not increasing with above mentioned use-cases. You can safely close this this.

**Comment by manoj-helpshift** [comment]
I further checked, in basic use-case, thread count is not creasing. But in some edge case still thread count increased but needs to identifyy the exact use-case.
We will release this change in our production service and will monitor it.

**Comment by IGJoshua** [comment]
Alright, sounds good. Open a new issue once you have more information about when it occurs.
