### ISSUE TITLE
S

### ISSUE THREAD

**Issue by SamTheone1** [IGJoshua/discljord#68]
**Describe the bug**

**Version Information**
 - Clojure Version:
 - Discljord Version:
 - OS bot is hosted on:

**To Reproduce**

Minimal reproduction case:
Add a github link to a repo which includes a minimal reproduction case (if possible).

**Expected behavior**

**Logs**
If possible, add logs from discljord at around the time the bug occurred. Ideally the logging level will have been set to `:debug` or `:trace` for the discljord namespaces.

**Additional context**

**Comment by IGJoshua** [comment]
Hey, thanks for opening an issue! Maybe next time I can be of some help if you fill out the template. :)
