### ISSUE TITLE
How to pass arguments into dispatch-handlers partially applied

### ISSUE THREAD

**Issue by lensgolda** [IGJoshua/discljord#76]
Hi, how to pass arguments, or is it possible at all, in [that](https://github.com/IGJoshua/discljord#declarative-event-handlers) example with partial applied `dispatch-handlers`.

```clojure
(partial dispatch-handlers #'handlers)
```

In code above, next two arguments to dispatch-handlers are event-type and event-data, so to pass any args, i somehow should be able to skip event-type and event-data.

I will be gratefull for the answer! Thanks.

**Comment by JohnnyJayJay** [comment]
I take it you want to pass arguments to your event handler functions. You could do it like this for example:
```clj
(fn [event-type event-data]
  (dispatch-handlers handlers event-type event-data my-arg1 my-arg2))
```
Those args will come after event type and event data.

**Comment by lensgolda** [comment]
Yep, thanks!

**Comment by JohnnyJayJay** [comment]
For future questions like this or if you just want to chat about discljord and Clojure, feel also free to [join the Discljord Discord server](https://discord.gg/discljord). It may be quicker and more convenient than issues for smaller questions :slightly_smiling_face:

**Comment by lensgolda** [comment]
Sure, i will
