### ISSUE TITLE
Content-Type headers are sent with requests without a body

### ISSUE THREAD

**Issue by JohnnyJayJay** [IGJoshua/discljord#81]
**Describe the bug**
Currently, the `Content-Type: application/json` header is sent with every request, including ones that do not have a body.
This leads to certain endpoints not working as intended/at all (so far I've only found this issue with `leave-guild!`).

**Version Information**
 - Clojure Version: any
 - Discljord Version: 1.2.3 and prior
 - OS bot is hosted on: any

**To Reproduce**
- Use `leave-guild!` and see it fail, although it should succeed (it responds with Bad Request)

**Expected behavior**
`Content-Type` should only be sent if there is a body. It should be omitted otherwise.

**Logs**
/

**Additional context**
/

**Comment by IGJoshua** [comment]
Already fixed on develop

**Comment by JohnnyJayJay** [comment]
Sorry, missed that then
