### ISSUE TITLE
Spec failing on rate limits

### ISSUE THREAD

**Issue by kiranshila** [IGJoshua/discljord#88]
**Describe the bug**
When instrumenting a complete bot, I see sepc errors that `#'discljord.messaging.impl/step-agent did not conform to spec. `
Specifically, 
```clojure
{:clojure.spec.alpha/problems 
   ({:path [:process :discljord.messaging.specs/rate-limits]
     :pred (discljord.specs/atom-of? (clojure.spec.alpha/map-of clojure.core/string? :discljord.messaging.specs/rate-limit-family))
```

**Version Information**
 - Clojure Version: 1.11.0-alpha2
 - Discljord Version: 1.3.0-RC2
 - OS bot is hosted on: Arch btw
 - JDK 17

**To Reproduce**
Run bot with full instrumentation

**Expected behavior**
No errors

**Comment by IGJoshua** [comment]
Fixed as of the release branch on 1.3.0, release soon to follow
