### ISSUE TITLE
how to respond to component interactions?

### ISSUE THREAD

**Issue by tommy-mor** [IGJoshua/discljord#93]
https://discord.com/developers/docs/interactions/message-components#responding-to-a-component-interaction

I have a button component, and when I press it in discord I receive an event in the bot.

This event is of type ``:interaction-create`` and its data has fields including ``id token data``

the ``:data`` key is correctly which button is pressed, so I know the event is correct.

My question is, how can I respond to that message. In the docs (linked above) it seems like I have to respond directly to the request. Not sure how to do that. I have an id and a token, so I tried calling execute-webhook with those, but that did not work.

what am I missing here?

**Comment by IGJoshua** [comment]
Interaction support is planned for 1.3.0, which is in a release candidate status.

If you work with the release candidate dependency, you can call interaction-specific functions, which are documented in the link below.

https://github.com/IGJoshua/discljord/blob/1.3.0-RC2/src/discljord/messaging.clj#L837

**Comment by tommy-mor** [comment]
ah, thank you.
